dtest <- read.table("test/X_test.txt")
dtrain <- read.table("train/X_train.txt")
dt <- rbind(dtest,dtrain)
feature <- read.table("features.txt",stringsAsFactors = FALSE)
subdt <- dt[,grep(pattern = "mean\\(\\)|std\\(\\)",x = feature$V2)]
testlab <- read.table("test/y_test.txt")
trainlab <- read.table("train/y_train.txt")
dtlab <- rbind(testlab,trainlab)
act <- read.table("activity_labels.txt")
library(dplyr)
dtlab <- mutate(dtlab,Activities=act$V2[V1])
subdt <- cbind(Activities=dtlab[,2],subdt)
names(subdt)[-1] <- feature$V2[grep(pattern = "mean\\(\\)|std\\(\\)",x = feature$V2)]
sbjte <- read.table("test/subject_test.txt")
sbjtr <- read.table("train/subject_train.txt")
sbj <- rbind(sbjte,sbjtr)
subdt <- cbind(Subject=sbj$V1,subdt)
library(reshape2)
df <- melt(subdt,id.vars = 1:2)
castdf <- dcast(df,Subject+Activities~variable,mean)
write.table(x = castdf,file = "Tidy_dataset.txt",row.names = FALSE) 